FROM dwyane/openjdk:8
MAINTAINER chenzhendong "631665415@@qq.com"
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
WORKDIR /usr/local/docker
COPY hrserver-0.0.1-SNAPSHOT.jar /root
CMD java -jar /root/hrserver-0.0.1-SNAPSHOT.jar


