FROM zhangde/dataflow-oracle-source:v8
MAINTAINER chenzhendong "631665415@@qq.com"
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
WORKDIR /usr/local/docker
