# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：  
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   开发环境：java -jar my-spring-boot.jar --spring.profiles.active=dev    
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod  

server:
  port: 1032
  servlet:
    context-path: /information-service   
spring:  
  profiles:  
    active: dev
  application:
    name: information-service  
#  security:
#    enabled: false

# 启用日志颜色
#  output: 
#    ansi: 
#      enabled: always
#logging:  
#  level:
#    root: INFO # mapper 接口所在的包设置为 debug
#  file: ./logs/information.log
#  pattern: 
#    console: %d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %clr(%logger){cyan} %clr(%msg%n){green}  
#    file: %d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n
#logging.level.com.×××.mapper=DEBUG
# 在当前项目下生成日志文件

#开启feign hystrix
feign:
  hystrix:
    enabled: true
  #ribbon的超时时间 重试次数
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试 
  eureka: #根据erueka 开启负载均衡
    enabled: true 
  # 设置hystrix的超时时间,默认为1000
  #用于禁用Hystrix的超时时间
#hystrix.command.default.execution.timeout.enabled=false
hystrix:
    command:
        default:
            execution:
              timeout:
                enabled: true
              isolation:
                    thread:
                        timeoutInMilliseconds: 9000    
   