#!/bin/bash
# author: lyc
# date:2019/9/10

# ===============    用户输入IP 地址信息      ==========================

echo "请输入你的网段，默认为 100"
echo "input you network segment, default is 100"
net_duan=100
read net_in
if [ ${#net_in} == 3 ]
then 
	net_duan=$net_in
fi

echo "网段为："$net_duan
echo "network segment："$net_duan


echo "请输入你的IP，默认为 101"
echo "input your IP，default is 101"
net_ip=101
read net_t
if [ ${#net_t} == 3 ]
then 
	net_ip=$net_t
fi

echo IP为：$net_ip


#  --------------  修改文件 ----------------
# 文件名称
filename_t="/root/ifcfg-eth0"
file_ip="/etc/sysconfig/network-scripts/ifcfg-eth0"

echo "--------------------------------------------------"

cat>$filename_t<<EOF
DEVICE=eth0

TYPE=Ethernet
ONBOOT=yes
# 实时生效，修改后无需要重启网卡立即生效
NM_CONTROLLED=yes
BOOTPROTO=static

DEFROUTE=yes
IPV6INIT=no
NAME="System eth0"
# 是否允许非root 用户控制此设备
USERCTL=no
# 同步DNS 设置 默认 yes
PEERDNS=yes

DNS1=192.168.${net_duan}.2
IPADDR=192.168.${net_duan}.${net_ip}
NETMASK=255.255.255.0
GATEWAY=192.168.${net_duan}.2

EOF
cat $filename_t

echo "以上内容将写入 ${file_ip}"
echo "above content will be written to ${file_ip}"
echo "please confirm：(y/n)"

read confirm
if [ $confirm == n ]
then
	echo "byebye"
	exit 1
fi

mv $filename_t /etc/sysconfig/network-scripts/ifcfg-eth0
rm -rf $filename_t

echo "设置 /etc/udev/rules.d/70-persistent-net.rules 文件 "
echo "setting /etc/udev/rules.d/70-persistent-net.rules "
# 获得MAC 地址
mac=`cat /sys/class/net/eth0/address`
# 文件名称
filename_t="/root/70-persistent-net.rules"
file_rule="/etc/udev/rules.d/70-persistent-net.rules"

cat>$filename_t<<EOF
# This file was automatically generated by the /lib/udev/write_net_rules
# program, run by the persistent-net-generator.rules rules file.
#
# You can modify it, as long as you keep each rule on a single
# line, and change only the value of the NAME= key.

# PCI device 0x8086:0x100f (e1000)
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="$mac", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"
EOF

echo "--------------------------------------------------"
cat $filename_t
echo "以上内容将写入 ${file_rule}"
echo "above content will be written to ${file_rule}"
echo "please confirm ：(y/n)"
read confirm
if [ $confirm == n ]
then
	echo "byebye"
	exit 1
fi

mv $filename_t $file_rule

echo "写入完成，是否重启网络,请确认：(y/n)"
echo "Write completed, whether to restart the network, please confirm：(y/n)"
read confirm
if [ $confirm == n ]
then
	echo "byebye"
	exit 1
fi

echo 'service network restart'

service network restart




