#logging:
#  level:
#    ROOT: DEBUG

server:
  port: 8889
#  servlet:
#    context-path: /demo # 服务的路径，不写默认为空
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1025/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/sdrfengmi_learn/study.git
          #          uri: https://github.com/sdrfengmi/javaStudy.git
          #          search-paths: bigData/java-spring/config-server/gateway-server
          #          skip-ssl-validation: true 用于git 登录使用ssl  skipSslValidation: true
          #          uri: https://github.com/sdrfengmi/javaStudy/tree/master/bigData/java-spring/config-server  这个地址github连接不上
          username: sdrfengmi
          password: zd521707
          #子目录 git仓库地址下的相对地址，可以配置多个，用,分割。 /** 标识全部
          search-paths: config-server/**
          #          search-paths: bigData/java-spring/config-server/gateway-server,bigData/java-spring/config-server/information-service,bigData/java-spring/config-server/quotes-service,bigData/java-spring/config-server/trade-service
          #          default-label: master tree/master/
          #            searchPaths: '{profile}'  # client客户端配置
          #            label: 20190405_trunk label   #配置仓库的分支,config client上能用到



      #----------------------------------- 2 svn配置
      #     enabled: true
      #      server:
      #        svn:
      #          uri: http://10.60.18.80/repos/doc/工程类项目/01_工程项目/P2018021_MAC版页面交易项目/源码/中间件源码/config-server
      #          username: chenzhendong
      #          password: 123444
      #          default-label: trunk
      #          search-paths: configuration-variables/quotes-service;configuration-variables/information-service

      #  profiles:
      #    active: subversion

      #暴露所有端点 请求的端点
      #management:
      #  endpoints:
      #    web:
      #      exposure:
      #         include: bus-refresh
      #        include: "*"

      #  -------------------------------------1 本地配置  -读取多个文件
      #  profiles:
      #    active: native
      #  cloud:
      #    config:
      #      server:
      #        native:
      #          search-locations:
      #           - classpath:/**
      #           - classpath:/configuration-variables/information-service/
      #           - classpath:/configuration-variables/gateway-server/
      #           - classpath:/configuration-variables/quotes-service/
      #           - classpath:/configuration-variables/trade-service/
      #          basedir: target/config  指定配置文件位置

